drenso_shared:
  public_services: false # Set whether all services must be public
  api:
    convert_entity_validation_exception:
      enabled: false # When enabled, the exception will be converted to a JSON response
      controller_prefix: 'App\\Controller\\Api\\' # The controller prefix to convert the exception for.
      data_field: 'payload'
  commands:
    check_action_security:
      enabled: true # Enable the drenso:check:action-security command (automatically true when you specify any of the options below and omit this line)
      excluded_controllers: ~ # Add a list of excluded controllers here
  database:
    softdeletable:
      enabled: false # Enable the softdeletable subscriber for injection (automatically true when you specify any of the options below and omit this line)
      use_gedmo_workaround:
        enabled: true # Whether to use the gedmo workaround (automatically true when you specify any of the options below and omit this line)
        use_utc: true # Whether to use UTC conversion
  email:
    mailer:
      enabled: false # Enable the e-mail service (automatically true when you specify any of the options below and omit this line)
      sender_email: ~ # The default sender email address: required when the e-mail service is enabled
      sender_name: ~ # The default sender name, can be empty
      translate_sender_name: true # When set, the configured sender_name will be translated in the 'messages' domain
  serializer:
    handlers:
      decimal: false # Enable the decimal handler
    static_serializer: false # Static serializer
    twig_integration:
      enabled: false # Enable the JMS twig integration (automatically true when you specify any of the options below and omit this line)
  services:
    feature_flags:
      enabled: true # Enable the feature flags service and annotations (automatically true when you specify any of the options below and omit this line)
      configuration_file: '' # The JSON file location where your flags are configured, for example '%env(resolve:FEATURES_FILE)%'
      configuration_local_file: '' # Not required, but can be used to override flags in the main configuration file outside of version control
    gravatar:
      enabled: true # Enable the GravatarHelper for injection (automatically true when you specify any of the options below and omit this line)
      fallback_style: 'mp' # Define a fallback style for accounts without a gravatar, see https://en.gravatar.com/site/implement/images/#default-image
      twig_integration:
        enabled: true # Enable the Gravatar twig integration (automatically true when you specify any of the options below and omit this line)
    ical_provider: false # Enable the IcalProvider for injection
    spreadsheethelper: false # Enable the SpreadsheetHelper for injection
