drenso_shared:
  api:
    convert_entity_validation_exception:
      enabled: false # When enabled, the exception will be converted to a JSON response
      controller_prefix: 'App\\Controller\\Api\\' # The controller prefix to convert the exception for.
  database:
    softdeletable:
      enabled: false # Enable the softdeletable subscriber for injection (automatically true when you specify any of the options below and omit this line)
      use_gedmo_workaround:
        enabled: true # Whether to use the gedmo workaround (automatically true when you specify any of the options below and omit this line)
        use_utc: true # Whether to use UTC conversion
  email:
    mailer:
      enabled: false # Enable the e-mail service (automatically true when you specify any of the options below and omit this line)
      sender_email: ~ # The default sender email address: required when the e-mail service is enabled
      sender_name: ~ # The default sender name, can be empty
      translate_sender_name: true # When set, the configured sender_name will be translated in the 'messages' domain
  serializer:
    handlers:
      decimal: false # Enable the decimal handler
    static_serializer: false # Static serializer
    twig_integration:
      enabled: false # Enable the JMS twig integration (automatically true when you specify any of the options below and omit this line)
  services:
    gravatar:
      enabled: true # Enable the SpreadsheetHelper for injection (automatically true when you specify any of the options below and omit this line)
      fallback_style: 'mp' # Define a fallback style for accounts without a gravatar, see https://en.gravatar.com/site/implement/images/#default-image
    ical_provider: false # Enable the IcalProvider for injection
    spreadsheethelper: false # Enable the SpreadsheetHelper for injection
