stages:
  - prepare
  - cs-fix
  - lint
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

variables:
  COMPOSER_MEMORY_LIMIT: -1
  YAMLLINT_DIRECTORIES: config/packages
    
include:
  - project: 'intern/runner-templates'
    file: '/symfony/install-dependencies.yml'
    ref: "16.5"
  - project: 'intern/runner-templates'
    ref: "16.5"
    file: '/php/code-style-fixer.yml'
  - project: 'intern/runner-templates'
    ref: "16.5"
    file: '/php/phpstan.yml'
  - project: 'intern/runner-templates'
    file: '/php/composer-require-checker.yml'
    ref: "16.5"
  - project: 'intern/runner-templates'
    file: '/php/composer-unused.yml'
    ref: "16.5"
  - project: 'intern/runner-templates'
    file: '/yaml/yamllint.yml'
    ref: "16.5"
  - project: 'intern/runner-templates'
    file: '/deploy/deploy.yml'
    ref: "16.5"

install-dependencies:
  before_script:
    - /bin/true
  except:
    - main
    - tags

yaml-analysis:
  except:
    - schedules
    - tags
    - main

composer-require-checker:
  except:
    - schedules
    - tags
    - main

composer-unused:
  except:
    - schedules
    - tags
    - main

deploy-staging:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_BRANCH
      when: on_success
    - when: never

deploy-production:
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  release:
    name: Release $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    description: 'Tagged release: $CI_COMMIT_TAG'
