stages:
  - prepare
  - cs-fix
  - lint
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

variables:
  COMPOSER_MEMORY_LIMIT: -1
  YAMLLINT_DIRECTORIES: config/packages
    
include:
  - project: 'intern/runner-templates'
    file: '/symfony/install-dependencies.yml'
    ref: "10.1"
  - project: 'intern/runner-templates'
    ref: "10.1"
    file: '/php/code-style-fixer.yml'
  - project: 'intern/runner-templates'
    file: '/php/phan.yml'
    ref: "10.1"
  - project: 'intern/runner-templates'
    file: '/php/composer-require-checker.yml'
    ref: "10.1"
  - project: 'intern/runner-templates'
    file: '/php/composer-unused.yml'
    ref: "10.1"
  - project: 'intern/runner-templates'
    file: '/yaml/yamllint.yml'
    ref: "10.1"
  - project: 'intern/runner-templates'
    file: '/deploy/deploy.yml'
    ref: "10.1"

install-dependencies:
  before_script:
    - /bin/true
  except:
    - master
    - tags

php-analysis:
  except:
    - schedules
    - tags
    - master

yaml-analysis:
  except:
    - schedules
    - tags
    - master

composer-require-checker:
  except:
    - schedules
    - tags
    - master

composer-unused:
  except:
    - schedules
    - tags
    - master

deploy-staging:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_BRANCH
      when: on_success
    - when: never

deploy-production:
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
