stages:
  - prepare
  - lint
  - deploy

variables:
  COMPOSER_MEMORY_LIMIT: -1
    
include:
  - project: 'intern/runner-templates'
    file: '/symfony/install-dependencies.yml'
  - project: 'intern/runner-templates'
    file: '/php/phan.yml'
  - project: 'intern/runner-templates'
    file: '/yaml/yamllint.yml'
  - project: 'intern/runner-templates'
    file: '/deploy/deploy.yml'

install-dependencies:
  before_script:
    - /bin/true
  except:
    - tags

php-analysis:
  except:
    - schedules
    - tags
    - master

yaml-analysis:
  script:
    - yamllint -c tests/yamllint/config src/Resources/config
  except:
    - schedules
    - tags
    - master

deploy-staging:
  only:
    - master
    - branches

deploy-production:
  only:
    - tags
