stages:
  - prepare
  - lint

install-dependencies:
  stage: prepare
  image: drenso/php:7.3-d3
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_cache"
    expire_in: 1 hour
    paths:
      - var/cache/
      - vendor/
  script:
    - composer install --no-interaction --no-progress --no-suggest
  after_script:
    - find vendor/ -name .git -type d -exec rm -rf {} \+
  tags:
    - docker

php-analysis:
  stage: lint
  image:
    name: kickin/phan:1.2.8
    entrypoint: [ "" ]
  dependencies:
    - install-dependencies
  script:
    - php7 /opt/phan/phan -k tests/phan/config.php
  tags:
    - docker
  except:
    - schedules
    - master
    - production

yaml-analysis:
  stage: lint
  image: kickin/yamllint:1.0.0
  dependencies: []
  script:
    - yamllint -c tests/yamllint/config src/Resources/config
  tags:
    - docker
  except:
    - schedules
    - master
    - production
