stages:
  - prepare
  - cs-fix
  - lint
  - deploy

variables:
  COMPOSER_MEMORY_LIMIT: -1
  YAMLLINT_DIRECTORIES: config/packages
    
include:
  - project: 'intern/runner-templates'
    file: '/symfony/install-dependencies.yml'
    ref: "5.1"
  - project: 'intern/runner-templates'
    ref: "5.1"
    file: '/php/code-style-fixer.yml'
  - project: 'intern/runner-templates'
    file: '/php/phan.yml'
    ref: "5.1"
  - project: 'intern/runner-templates'
    file: '/php/composer-require-checker.yml'
    ref: "5.1"
  - project: 'intern/runner-templates'
    file: '/php/composer-unused.yml'
    ref: "5.1"
  - project: 'intern/runner-templates'
    file: '/yaml/yamllint.yml'
    ref: "5.1"
  - project: 'intern/runner-templates'
    file: '/deploy/deploy.yml'
    ref: "5.1"

install-dependencies:
  before_script:
    - /bin/true
  except:
    - master
    - tags

php-analysis:
  except:
    - schedules
    - tags
    - master

yaml-analysis:
  except:
    - schedules
    - tags
    - master

composer-require-checker:
  except:
    - schedules
    - tags
    - master

composer-unused:
  except:
    - schedules
    - tags
    - master

deploy-staging:
  only:
    - master
    - branches

deploy-production:
  only:
    - tags
